nginx-ingress:
  controller:
    hostNetwork: true
    service:
      externalIPs:
        - {{ .Ingress.ExternalIp }}
    nodeSelector:
      kubernetes.io/hostname: {{ .Ingress.NodeSelector }}
prometheus:
  alertmanager:
    persistentVolume:
      enabled: False
  server:
    persistentVolume:
      enabled: False
    ingress:
      enabled: True
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: ingress-auth-prometheus
        nginx.ingress.kubernetes.io/auth-realm: "Authentication required to access Prometheus."
      hosts:
        - {{ .Prometheus.Host }}
      tls:
      - hosts:
        - {{ .Prometheus.Host }}
        secretName: {{ .Prometheus.Host }}
